name: Do stuff

# Controls when the workflow will run
on:
  push:
    branches: [ main, dev ]
defaults:
  run:
    working-directory: myfolder\myfolder2

jobs:
  build:
    runs-on: [windows-2019]
    steps:
      - uses: actions/checkout@v2

      - name: Replace tokens in .npmrc template
        uses: cschleiden/replace-tokens@v1
        with:
          files: .npmrc
          tokenPrefix: "{{"
          tokenSuffix: "}}"
        env:
          VERSION: 3.3.3
        continue-on-error: false
      
      - name: print .npmrc template
        run: cat .npmrc
