name: Do stuff

# Controls when the workflow will run
on:
  push:
    branches: [ main, dev ]
defaults:
  run:
    working-directory: myfolder\myfolder2

jobs:
  build:
    runs-on: [windows-2019]
    steps:
      - uses: actions/checkout@v2
      
      - name: Print current dir
        run: dir

      - name: Replace
        uses: cschleiden/replace-tokens@v1.1
        with:
          tokenPrefix: '{{'
          tokenSuffix: '}}'
          files: '[".npmrc"]'
        env:
          VERSION: 3.2.1
      
      - name: print .npmrc template
        run: cat .npmrc
