name: Do stuff

# Controls when the workflow will run fagh
on:
  push:
    branches: [ main, dev ]
defaults:
  run:
    working-directory: myfolder\myfolder2

jobs:
  build:
    runs-on: [windows-2019]
    steps:
      - uses: actions/checkout@v1
      
      - name: Print current dir
        run: dir
        
      - uses: cschleiden/replace-tokens@v1
        with:
          files: '["${{github.workspace}}/.npmrc"]'
          tokenPrefix: '{{'
          tokenSuffix: '}}'
        env:
          VERSION: "3.2.1"

      - name: print .npmrc template
        run: cat .npmrc
